
[default.extend-words]
fov = "fov"
FoV = "FoV"
FOV = "FOV"
mis = "mis"
MIS = "MIS"
Ba  = "Ba"
Fo  = "Fo"
tht = "tht"
SER = "SER"
pn  = "pn"
Optin = "Optin"
ptd = "ptd"

[default]
check-strings = true
